name: Repo Creation Issue
description: Create a new repository
title: "[NEW_REPO]: Criação de um novo repositório"
labels: ["project"]
body:
  - type: markdown
    attributes:
      value: |
        Para criar um novo repositório, preencha as seguintes informações. Por favor, note que o nome do projeto deve ser único e a descrição deve ser clara e concisa. Não altere o título do problema começando com [NEW_REPO].
  - type: input
    id: project_name
    attributes:
      label: project_name
      description: Qual é o nome do projeto?
      placeholder: ex. meu_novo_projeto
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: description
      description: Sobre o que é o projeto?
      placeholder: ex. Este projeto é sobre...
    validations:
      required: true
  - type: dropdown
    id: privacy_type
    attributes:
      label: privacy_type
      description: Qual é o tipo de privacidade do repositório?
      options:
        - public
        - private
    validations:
      required: true
  - type: dropdown
    id: team
    attributes:
      label: team
      description: Qual equipe será responsável por este projeto?
      options:
        - Back-end
        - Front-end
    validations:
      required: false
